global:
  scrape_interval:     15s

  external_labels:
    monitor: 'game-service-monitor'

scrape_configs:
- job_name: 'game-service'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['173.193.82.62:32131']
  scheme: http
  tls_config:
    insecure_skip_verify: true
- job_name: 'player-service'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['173.193.82.62:30554']
  scheme: http
  tls_config:
    insecure_skip_verify: true
- job_name: 'auth-service'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['173.193.82.62:30082']
  scheme: http
  tls_config:
    insecure_skip_verify: true
- job_name: 'frontend'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['173.193.82.62:30935']
  scheme: http
  tls_config:
    insecure_skip_verify: true