apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: game
  name: game
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: game
    spec:
      containers:
      - image: docker.io/yasminaumeeruddy/libertybikes-game
        env:
        - name: org_libertybikes_restclient_PlayerService_mp_rest_url
          value: http://player:8081
        name: game
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: game
  name: game
spec:
  ports:
  - name: "8080"
    port: 8080
    nodePort: 32131
  type: NodePort
  selector:
    io.kompose.service: game