apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: player
  name: player
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: player
    spec:
      containers:
      - image: docker.io/yasminaumeeruddy/libertybikes-player
        name: player
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: player
  name: player
spec:
  ports:
  - name: "8081"
    port: 8081
    nodePort: 30554
  type: NodePort
  selector:
    io.kompose.service: player